spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${USER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=event-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${EVENT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/events/**

spring.cloud.gateway.server.webmvc.routes[2].id=booking-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${BOOKING_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/bookings/**
