spring.application.name=booking-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub_bookings
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

user-service.url=http://localhost:8081
event-service.url=http://localhost:8082